site_name: Young/*
site_url: https://youngcharleslucas.github.io
theme:
  name: material 
  font: 
    text: Source Serif 4 
  icon: 
    logo: material/square-outline
  favicon: assets/images/dot-circles.svg
  palette: 
    primary: custom  
  features: 
    - toc.integrate  
    - navigation.indexes

  custom_dir: overrides

extra: 
  social: 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/charles-lucas-young/


extra_css: 
  - stylesheets/extra.css

# Uncomment for offline build
# plugins:
#   - offline 

extra_javascript:
  - javascripts/drawer-toggle.js
  - javascripts/header-title.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight: 
      anchor_linenums: true 
      line_spans: __span  
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid  
          class: mermaid  
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.arithmatex:
      generic: true
  - admonition  
  - pymdownx.details 

# nav: 
#   - Bio: index.md  
#   - Setup: setup.md  
#   - WGU Notes: 
#     - url: WGU_Notes/
#       name: WGU Notes
#       use_directory_urls: true
#     # - D333 Ethics in Tech: WGU_Notes/D333_Ethics_in_Tech/D333_ethics_in_tech.md  
#     # - C191 Operating Systems: WGU_Notes/C191_Operating_Systems/c191_Operating_Systems.md
#     # - C949 Data Structures I: WGU_Notes/C949_Data_Structures_I/C949_Data_Structures_I.md
#     # - C950 Data Structures II:  WGU_Notes/C950_Data_Structures_II/C950_Data_Structures_II.md
#     # - C951 AI: WGU_Notes/C951_AI/C951_ai.md
#     # - C960 Discrete Math II:  WGU_Notes/C960_Discrete_Math_II/C960_Discrete_Math_II.md
#     # - D284 Software Engineering:  WGU_Notes/D284_Software_Engineering/D284_Software_Engineering.md
#     # - D286 Communication:  WGU_Notes/D268_Communication/D268_Communication.md  
#     # - D287 Java Frameworks:  
#     #   - Searching and Algorithms: WGU_Notes/D287_Java_Frameworks/Searching_and_Algorithms/Search_and_Algo.md
#     #   - Unit Testing: WGU_Notes/D287_Java_Frameworks/Unit_Testing/Unit_Testing.md  
#     #   - Exceptions: WGU_Notes/D287_Java_Frameworks/Exceptions/Exceptions.md  
#     #   - Generics: WGU_Notes/D287_Java_Frameworks/Generics/Generics.md  
#     #   - Collections: WGU_Notes/D287_Java_Frameworks/Collections/Collections.md  
#     #   - Additional Material: WGU_Notes/D287_Java_Frameworks/Additional_Material/Additional_Material.md  
#     # - D288 Backend Programming:  WGU_Notes/D288_Backend_Programming/D288_Backend_Programming.md  
#     # - D336 Business in IT: WGU_Notes/D336_Business_IT/D336_business_it.md    
#     # - D387 Advanced Java:  WGU_Notes/D387_Advanced_Java/D387_Advanced_Java.md
#     # - D480 Software QA: WGU_Notes/D480_Software_QA/D480_Software_QA.md
#   - Library: 
#     - Algorithms and Data Structures: 
#       - Algorithms Intro: Library/Data_Structures_and_Algos/basics.md
#     - Frontend Masters:  
#       - React v18:  
#         - React Intro: Library/Frontend_Masters/react_v18/intro.md  
#         - JSX: Library/Frontend_Masters/react_v18/jsx.md  
#         - React: Library/Frontend_Masters/react_v18/react.md  
#         - Testing: Library/Frontend_Masters/react_v18/testing.md 
#       - ASW for Frontend Eng.: Library/Frontend_Masters/aws_frontend_v2/aws_frontend_v2.md
#   - Quotes: Quotes.md
